sudo: required
dist: trusty
language: node_js
node_js:
- '9.2'
addons: 
apt:
  sources:
  - google-chrome
  packages:
  - google-chrome-stable
  - google-chrome-beta
  - icnsutils
  - graphicsmagick
cache:
  directories:
  - node_modules
  - "$HOME/.npm/_prebuilds"
  - "$HOME/.cache/electron"
  - "$HOME/.cache/electron-builder"
before_install:
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
before_script:
- export TRUE_COMMIT_MESSAGES=$(git log --oneline -2 | grep "+build")
- export TRUE_COMMIT=$(echo $TRUE_COMMIT_MESSAGES | awk '{print $1}')
- echo $TRUE_COMMIT_MESSAGES
- yarn install
script:
- echo 'Build Dist' && echo -en 'travis_fold:start:script.build\\r'
- yarn build --base-href="./"
- echo -en 'travis_fold:end:script.build\\r'
- echo 'Lint Codebase' && echo -en 'travis_fold:start:script.lint\\r'
- yarn run lint
- echo -en 'travis_fold:end:script.lint\\r'
- echo 'Test Codebase' && echo -en 'travis_fold:start:script.test\\r'
- yarn run travis:test
- echo -en 'travis_fold:end:script.test\\r'
- echo 'Done!'
after_script:
- npm run coveralls

deploy:
  provider: releases
  api_key:
    secure: cNBGotVsQNryv9oLJESOO2PjC3sjqpjHdF7G0vLB06flKFA1PiFxbWXcuPECr9+EFc6DApBfAuRmjDJNB0YSroOPQ7H1mGbKV0VcChlHei53aMnpznLxHLhFtM8npV6SB1fXzmRBxTM1p3pIflyH4n+Ja83A7P/9NHIcXa3Xyg66cOIU9oKS9AsZytcfzYQyvXJNIpz1DbIabJzoc29z5eqq1cj3JqUNpgiSPV4d4hhvoI4WfW5SjfLDNGxLNxD0TCnRpLIJmE0AXH4o5NQWT67hpugn/JMsPr09O87TZK1/v6djr988m1El9oqML9plyVRg569UEGAU+kI5Wa3deNK4aH7vWfm7Vmw+vKgeCQ3/lFEg38jdNMXfUX8jlO29+CqpNT3dgZD6+1wxn4qH9JSBGAEb1jnoleDco/wpzRWIsBt6uueHKgxMqFwdUHzGw8d0oFa4o1J/LBSQYD6RCI8+oKFOG2oRHN6bkmGRablbkFXefaP/0oqMvqs+2DTsv7R2uBmk5sAj43B6ImhLJUzn2OukniYXjkeaflY2vAUqny2Jd5ZI5YrJ8Y4L2RmPp55O5lNiRx4ZFmi1cs2/Rhs9napIaWWScbrBFQsJJ7B5tMiF49YQr+bIJbxuw0MYwW79FMv5UgxOa3MHHwMEMHP+/aDVYkKQBGDB9bSb7Yc=
  file: dist.zip
  overwrite: true
  on:
    repo: velescore/veles-desktop
    branch: develop

#deploy:
#  - provider: releases
#    api-key:
#    secure: cNBGotVsQNryv9oLJESOO2PjC3sjqpjHdF7G0vLB06flKFA1PiFxbWXcuPECr9+EFc6DApBfAuRmjDJNB0YSroOPQ7H1mGbKV0VcChlHei53aMnpznLxHLhFtM8npV6SB1fXzmRBxTM1p3pIflyH4n+Ja83A7P/9NHIcXa3Xyg66cOIU9oKS9AsZytcfzYQyvXJNIpz1DbIabJzoc29z5eqq1cj3JqUNpgiSPV4d4hhvoI4WfW5SjfLDNGxLNxD0TCnRpLIJmE0AXH4o5NQWT67hpugn/JMsPr09O87TZK1/v6djr988m1El9oqML9plyVRg569UEGAU+kI5Wa3deNK4aH7vWfm7Vmw+vKgeCQ3/lFEg38jdNMXfUX8jlO29+CqpNT3dgZD6+1wxn4qH9JSBGAEb1jnoleDco/wpzRWIsBt6uueHKgxMqFwdUHzGw8d0oFa4o1J/LBSQYD6RCI8+oKFOG2oRHN6bkmGRablbkFXefaP/0oqMvqs+2DTsv7R2uBmk5sAj43B6ImhLJUzn2OukniYXjkeaflY2vAUqny2Jd5ZI5YrJ8Y4L2RmPp55O5lNiRx4ZFmi1cs2/Rhs9napIaWWScbrBFQsJJ7B5tMiF49YQr+bIJbxuw0MYwW79FMv5UgxOa3MHHwMEMHP+/aDVYkKQBGDB9bSb7Yc=
#    file:
#      - $TRAVIS_BUILD_DIR/dist.zip
#      - $TRAVIS_BUILD_DIR/dist.zip.sha256sum.txt
#    overwrite: true
#    on:
#      tags: true
#
